boriel-basic/zxbasic

.gitignore, README, README.md, tests/api/test_symbolTable.py, tests/symbols/test_symbolARRAYACCESS.py, tests/symbols/test_symbolBASICTYPE.py, tests/symbols/test_symbolBINARY.py, tests/symbols/test_symbolBLOCK.py, tests/symbols/test_symbolBOUND.py, tests/symbols/test_symbolBOUNDLIST.py, tests/symbols/test_symbolFUNCDECL.py, tests/symbols/test_symbolFUNCTION.py, tests/symbols/test_symbolNUMBER.py, tests/symbols/test_symbolSENTENCE.py, tests/symbols/test_symbolSTRING.py, tests/symbols/test_symbolSTRSLICE.py, tests/symbols/test_symbolTYPE.py, tests/symbols/test_symbolTYPEALIAS.py, tests/symbols/test_symbolTYPECAST.py, tests/symbols/test_symbolVAR.py, tests/symbols/test_symbolVARARRAY.py, tox.ini
The only supported language at the momment will be
Python27 since Python3 versions are not working
at the momment.
=> Add basic Tox testing

tox.ini
Since it was deprecated in:
0619f4b570b6572baef4578f3ab9fabb4e2e969b
=> Remove temporal directory creation

arch/zx48k/translator.py, tests/functional/let_array_substr10.asm, tests/functional/let_array_substr11.asm, tests/functional/let_array_substr12.asm, tests/functional/let_array_substr13.asm, tests/functional/let_array_substr2.asm, tests/functional/let_array_substr3.asm, tests/functional/let_array_substr7.asm, tests/functional/let_array_substr9.asm
Asignation of substring to an array element of type String was
not working when the index was constant. Fixed.
LET m$(2)(3 TO 5) = "x"
Didn't update m$(2).
=> bugfix: Fix LET ARR$ substr asignation

tests/functional/substr_err.bas, zxbparser.py
When assiging a substr to an array string the parser might
crash if the array is not declared previously.
=> Fix parser crash when assigning substr

tests/functional/dim_test0.bas, zxbparser.py
When declaring a variable or constant referencing an address of an
element of an undeclared array, the compiler crashed. Fixed.
=> Fix crash when referencing undeclared arrays

tests/functional/callable_err.bas, zxbparser.py
Under some circunstances using an undefined array of strings
might crash the parser. Fixed.
=> Fix parser crash on wrong callable args

arch/zx48k/backend/__init__.py, tests/functional/headerless.asm, tests/functional/headerless.bas
When using the --headerless flag, the autostart was not working.
Fixed.
=> Bugfix: emmit start label in headless mode

api/check.py, arch/zx48k/translator.py, library-asm/letsubstr.asm, tests/functional/id_substr_eq_expr.asm, tests/functional/let_array_substr.asm, tests/functional/let_array_substr1.asm, tests/functional/let_array_substr10.asm, tests/functional/let_array_substr11.asm, tests/functional/let_array_substr12.asm, tests/functional/let_array_substr13.asm, tests/functional/let_array_substr2.asm, tests/functional/let_array_substr3.asm, tests/functional/let_array_substr5.asm, tests/functional/let_array_substr7.asm, tests/functional/let_array_substr9.asm, tests/functional/llc.asm, tests/functional/lvalsubstr_nolet.asm, tests/functional/strbase.asm, tests/functional/strbase2.asm, tests/functional/substrlval.asm, tests/functional/sys_letsubstr0.asm, tests/functional/sys_letsubstr0.bas, tests/functional/sys_letsubstr1.asm, tests/functional/sys_letsubstr1.bas, tests/functional/sys_letsubstr2.asm, tests/functional/sys_letsubstr2.bas
Expressions like LET a$(4) = "A" were causing a memory leak.
Fixed.
=> Fix error with LETSUBSTR

tests/functional/test_cmdline.txt, zxb.py
zxb -D ANYTHING
was crashing. Fixed.
=> Bugfix: Allow defining empty macros

api/symboltable.py, tests/functional/param_byref_warn.asm, tests/functional/param_byref_warn.bas, tests/functional/test_errmsg.txt
ByRef parameters should never warn if not used (read) within the function.
They can be used to return values (only writen).
=> Fix warning message in byref params

library-asm/usr_str.asm, tests/functional/fastcall0.asm, tests/functional/spfill.asm, tests/functional/usr0.asm
USR "x" returns the mem address of UDG "x". "x" can be uppercase, lowercase or
even the UDG itself
=> Make usr "a" to also use UDG

library-asm/usr_str.asm, tests/functional/fastcall0.asm, tests/functional/spfill.asm, tests/functional/usr0.asm, tests/runtime/usr_str.bas
Introduced when adding support for graphics characters
in USR.
=> Fix error in usr_str

tests/functional/str_base0.asm, tests/functional/str_base0.bas, tests/functional/str_base1.asm, tests/functional/str_base1.bas, tests/functional/str_base2.asm, tests/functional/str_base2.bas, tests/functional/str_base3.asm, tests/functional/str_base3.bas, tests/functional/str_base4.asm, tests/functional/str_base4.bas, tests/functional/str_base5.asm, tests/functional/str_base5.bas, zxbparser.py
Not used when assigning a subtring of in an array element. It should be
used. Fixed.
=> Fix string base not being used

tests/runtime/check_test.py, tests/runtime/update_test.py
This will allow me to remove/hide the deprecated counterparts. Will need pulling the latest changes from the emulator repo. Sorry for bothering. :-)
=> Switch from using deprecated zx emulator members.

bin/zxb, bin/zxbasm, bin/zxbc, bin/zxbpp, setup.py, zxbc.py
Also deprecates zxb in favour if zxbc
=> Update setup script

outfmt/__init__.py, outfmt/binary.py, outfmt/codeemitter.py, outfmt/tzx.py, zxb/__init__.py, zxb/zxb.py, zxbasm/asmparse.py
Not sure if this aligns with your plans, but this at least gives the idea on what might be sufficient for #304. :-)
=> [#304] Support custom code emitters.

tests/runtime/check_test.py, tests/runtime/update_test.py
This would help to resolve https://github.com/kosarev/zx/issues/10 and make sure we don't even attempt to compare screenshots when the emulation is terminated due to reasons other than hitting the breakpoint, e.g., pressing `F10`.
=> [Tests] Use exceptions for quitting from the emulation loop.

symbols/bound.py, symbols/var.py
If it's a constant we don't need to resolve it outside. It
comes resolved (for constants of constants)
=> SymbolVAR always return its final value

arch/zx48k/backend/__init__.py, tests/functional/const7.asm, tests/functional/const7.bas
Sometimes the type length was not correctly guessed
in local variables initialization from a CONST
=> Fix local variable initalization

api/optimize.py, ast_/ast.py, ast_/tree.py, tests/functional/opt2_unused_var.asm, tests/functional/opt2_unused_var.bas
LET y = funcCall(x)
If y is not used and optimized, the funcCall(x) must be
compiled anyway.
=> Ensure function calls on some optimizations cases

api/optimize.py, tests/functional/lbound13.asm, tests/functional/lbound13.bas, zxb/zxbparser.py
LBOUND / UBOUND usage on param array should not be
optimized when the dimension requested is a constant value.
The dimensions for parameter arrays are not known.
=> Fix bug with constant LBOUND/UBOUND in param array

api/symboltable.py, tests/functional/include_error.bas, tests/functional/test_errmsg.txt
This happened when resolving pending calls. Filename
must be that of the variable (where the variable is
being referenced, not the current main file which is not
always the right one).
=> Fix wrong include name file

arch/zx48k/translator.py, tests/functional/byrefbyref.asm, tests/functional/byrefbyref.bas, tests/functional/byvalbyref.asm, tests/functional/byvalbyref.bas, tests/functional/localbyref.asm, tests/functional/localbyref.bas
Parameters of type Byte / Ubyte has an odd alignment.
When passing the address of such parameters in a function
call as a ByRef, the offset must be increased by one.
=> Fix bug when passing parameters

src/arch/zx48k/optimizer/basicblock.py, src/arch/zx48k/optimizer/patterns.py, src/arch/zx48k/peephole/evaluator.py, tests/arch/zx48k/optimizer/test_basicblock.py, tests/functional/opt4_due_0.asm, tests/functional/opt4_due_0.bas
When a memory access is of type (a * b + c...) etc,
it will check if any of a, b, c is used and mark them as
required to avoid bypassing dependencies.
=> Fix opt check for dependency

.github/workflows/python-app.yml, .travis.yml, tests/api/test_symbolTable.py, tests/arch/zx48k/optimizer/test_optimizer_asm.py, tests/symbols/test_symbolARRAYACCESS.py, tests/symbols/test_symbolBINARY.py, tests/symbols/test_symbolBOUND.py, tests/symbols/test_symbolTYPECAST.py, tox.ini
=> Create a python-app.yml

src/api/config.py, src/api/errmsg.py, src/libzxbc/zxbc.py, src/libzxbpp/zxbpp.py, tests/api/test_config.py, tests/functional/test_cmdline.txt, tests/functional/test_errmsg.txt
First N warnings will be silenced with --expect-warnings=N
command line option.
=> Allow silencing N warnings

src/arch/zx48k/library/input.bas, src/arch/zxnext/library/input.bas
When the input reaches the bottom-right corner of the
screen, in the user presses delete key the cursor is
misplaced.
=> Prevents cursor misplacement

src/arch/zx48k/library-asm/random.asm, tests/functional/mcleod.asm, tests/functional/opt4_keepix.asm, tests/functional/randomize.asm
Was not returning all the random bytes correctly
=> Fix RAND routine

src/arch/zx48k/library/input.bas, src/arch/zxnext/library/input.bas
PIP var (PEEK 23609) must be >= 1 for the sound to
be activated. Otherwise it's disabled.
=> Make INPUT to PIP on key pressing

src/arch/zx48k/library/input.bas, src/arch/zxnext/library/input.bas
Use POKE 23609, -1 (or 255) to mute it.
=> Make input to sound like original zx48 key taps

src/api/symboltable.py, src/zxbc/zxbparser.py, tests/functional/test_errmsg.txt
When using DECLARE in a functions with parameters
a warning about unused parameters was issued. Fixed.
=> Fix warning on declare functions

src/api/errmsg.py, src/zxbc/zxbparser.py, tests/functional/bad_pragma.asm, tests/functional/bad_pragma.bas, tests/functional/test_errmsg.txt
Unknown pragmas are ignored and a warning is emitted instead.
=> Fix crash on unknown pragma

src/zxbc/zxbparser.py, tests/functional/doloop4.asm, tests/functional/end.asm, tests/functional/fornextopt.asm, tests/functional/fornextopt2.asm, tests/functional/ifemptylabel1.asm, tests/functional/ifemptylabel2.asm, tests/functional/ongosub.asm, tests/functional/opt1_endtest.asm, tests/functional/test_errmsg.txt, tests/functional/whilefalse1.asm
If the last instruction in BASIC is an ender (END, STOP, GOTO,
RETURN) do not add an extra END. It's useless.
Fix for #511
=> Do not add redundant END

src/api/config.py, src/api/debug.py, src/api/errmsg.py, src/api/optimize.py, src/api/options.py, src/api/symboltable.py, src/arch/zx48k/backend/__init__.py, src/arch/zx48k/optimizer/__init__.py, src/arch/zx48k/optimizer/basicblock.py, src/arch/zx48k/translator.py, src/arch/zx48k/translatorvisitor.py, src/symbols/argument.py, src/symbols/paramdecl.py, src/zxbasm/asmlex.py, src/zxbasm/asmparse.py, src/zxbasm/zxbasm.py, src/zxbc/args_parser.py, src/zxbc/zxbc.py, src/zxbc/zxbparser.py, src/zxbpp/zxbpp.py, tests/api/test_config.py, tests/api/test_symbolTable.py, tests/functional/arrcheck.bas, tests/functional/break.bas, tests/functional/strict_bool.bas
Use a centralized naming compatible with python ID names,
and defined sitematically.
=> Refactorize config constants

.github/workflows/python-app.yml, .travis.yml, src/api/__init__.py, src/api/config.py, src/api/options.py, src/arch/zx48k/backend/__init__.py, src/outfmt/codeemitter.py, src/zxbc/args_config.py, src/zxbc/args_parser.py, src/zxbc/zxbc.py, src/zxbpp/zxbpp.py, tests/api/test_config.py, tests/api/test_symbolTable.py, tests/cmdline/config_sample.ini, tests/cmdline/test_zxb.py, tests/functional/test_cmdline.txt, tests/symbols/test_symbolARRAYACCESS.py, tests/symbols/test_symbolBINARY.py, tests/symbols/test_symbolBOUND.py, tests/symbols/test_symbolTYPECAST.py, tox.ini
This refact moves part of the OPTIONS config done after
args parsing.
=> Isolate config setup into a module

src/api/check.py, src/arch/zx48k/translator.py, src/symbols/argument.py, tests/functional/bad_fname_err0.bas, tests/functional/bad_fname_err1.bas, tests/functional/bad_fname_err2.bas, tests/functional/bad_fname_err3.asm, tests/functional/bad_fname_err3.bas, tests/functional/bad_fname_err4.bas, tests/functional/test_errmsg.txt
Some messages uses the original (initial) filename,
because the error is detected at semantic stage. This can
be misleading to the programmer.
=> fix: put correct fname in error messages

docs/index.md, docs/library.md, docs/library/stdlib.md, docs/library/string.bas.md, docs/library/string/left.md, docs/library/string/mid.md, docs/library/string/right.md, poetry.lock, pyproject.toml
=> doc: start of string.bas library documentation

src/zxbpp/zxbpplex.py, tests/functional/prepro03.bi, tests/functional/prepro03.out, tests/functional/prepro80.bi, tests/functional/prepro80.out
Lines having a line comment with REM or ' and ending in a backslash \ were not continued. Now they are. This allows setting comments within multiline #define macros
=> fix: backlash continuation ignored after comment

src/arch/z80/backend/_32bit.py, src/arch/z80/visitor/builtin_translator.py, tests/functional/zx48k/peek_ubyte.asm, tests/functional/zx48k/peek_ubyte.bas, tests/functional/zx48k/peek_uinteger.asm, tests/functional/zx48k/peek_uinteger.bas, tests/functional/zx48k/peek_ulong.asm, tests/functional/zx48k/peek_ulong.bas
This implementation was wrong due to a edge case with iload32 IC translation.
=> fix: fixes PEEK(ULong, ...)

pyproject.toml, src/ply/lex.py
https://docs.astral.sh/ruff/rules/unused-import/
=> FIX: fix Ruff rule "unused-import" (F401)

src/__init__.py
For Python < 3.6 (at least) the error message
saying the Python version is unsupported crashed, because older versions do not support f-strings.
=> feat: do not crash in older Python versions

src/__init__.py
This fix will correctly display the message error
when a (very) old (Python 2.x) version of Python is used.
=> feat: shows error message in Python 2.x

pyproject.toml
Currently ruff format does not sort imports
(see https://github.com/astral-sh/ruff/issues/8926). This means that executing poe format was not sorting them which can cause errors during linting check in the pipeline.
=> build: update poe format command.

src/zxbc/zxbparser.py
In 3.12 this should be an StrEnum (not available in Python 3.10). Use the value instead.
=> fix: usage of enum with Python 3.12

poetry.lock, pyproject.toml
As of Python 3.12+ the module distutils is no longer built-in, but needs to be installed as a 3rd party module from the setuptools package.
This package is needed by our testing system, so it's a dev dependency.
=> build: add setuptools as a dev dependency

poetry.lock, pyproject.toml, tests/functional/test_.py
Also remove pytest-timeout since we're use our own timeout solution for test.
When using pytest-xdist the test time might fluctuate due to excessive parallelization and coverage meausre.
=> feat: increase test timeout

pyproject.toml, tests/functional/Makefile, tests/functional/cmdline/test_errmsg.txt, tests/functional/cmdline/test_loop_check.txt, tests/functional/cmdline/test_read_data.txt, tests/functional/test_.py, tests/functional/test_basic.py
Not needed anymore. Pytest will execute .txt files as doctest directly in a parallel way.
=> refact: remove test_errmsg method

src/arch/z80/optimizer/cpustate.py, tests/arch/zx48k/optimizer/test_cpustate.py
When using IX / IY regs, the assignation were not
correctly calculated. Fixed.
=> fix: fixes a bug in CPUState with IX regs

tests/runtime/cases/point.bas, tests/runtime/cases/screen_xy_shift.bas, tests/runtime/check_test.py, tests/runtime/run, tests/runtime/test_all, tests/runtime/test_case
Now if there's a line with a comment like
'PARAM: xxxx
the xxx will be pass as parameter to the compiler.
The timeout has been increased to 180secs (3 mins.)
=> test: fix runtime test

src/zxbc/args_parser.py, tests/functional/cmdline/test_cmdline.txt
IR stands for Intermediate Representation.
This format is used by ZXBasicStudio and is useful for inspection.
Also, the extension is now .ir instead of IR.
Some options helps have also been updated.
=> refact: change --format=IR to --format=ir

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/bug_report_es.yaml, CODE_OF_CONDUCT.md
Also add CODE_OF_CONDUCT.md file
=> feat: add Bug Report form

src/arch/z80/backend/_32bit.py, tests/functional/arch/zx48k/neq32.asm, tests/functional/arch/zx48k/neq32.bas
=> fix: neq32 had extra push af. Fixed.

src/api/optimize.py, tests/functional/arch/zx48k/warn_brk.asm, tests/functional/arch/zx48k/warn_brk.bas, tests/functional/cmdline/test_warning.txt
When using --enable break, RETURN within functions cause an Unreachable Code warning (the code after the RETURN was the BREAK check). Fixed.
Fixes #822
=> fix: do not emit spurious warning with --enable-break

src/api/check.py, tests/functional/arch/zx48k/do_crash.bas, tests/functional/cmdline/test_errmsg.txt
=> fix: crash when using do loop with bad type

src/api/optimize.py, tests/functional/arch/zx48k/warn_lbl.asm, tests/functional/arch/zx48k/warn_lbl.bas, tests/functional/cmdline/test_warning.txt
When using a label before of a RETURN
sentence within a function, a warning
was emitted. Fixed.
Fixes #822
=> fix: do not emit spurious warning

src/arch/z80/backend/runtime/core.py, src/lib/arch/zx48k/runtime/math/pow.asm, src/lib/arch/zxnext/runtime/math/pow.asm, tests/functional/arch/zx48k/addf.asm, tests/functional/arch/zx48k/addf.bas, tests/functional/arch/zx48k/fp_pow.asm, tests/functional/arch/zx48k/fp_pow.bas, tests/functional/arch/zx48k/mulf16.asm, tests/functional/arch/zx48k/mulf16.bas, tests/functional/arch/zx48k/read10.asm, tests/functional/arch/zx48k/read13.asm, tests/functional/arch/zx48k/read4.asm, tests/functional/arch/zx48k/read5.asm, tests/functional/arch/zx48k/read8.asm, tests/functional/arch/zx48k/read9.asm, tests/functional/arch/zxnext/fp_pow.asm, tests/functional/arch/zxnext/fp_pow.bas
=> refact: move runtime pow to math/ folder

docs/lbound.md, docs/ubound.md
=> doc: fixes using unescaped < > in Markdown

src/zxbpp/base_pplex.py, src/zxbpp/zxbpp.py, src/zxbpp/zxbpplex.py
The ZXBasic PreProcessor can be used from the command line if desired (i.e. as a linux pipe filter).
Passing no filename should allow this. Unfortunately, this was broken at some point during a refact (code split).
Also remove duplicated constants and use base constants for the stdin filename.
=> fix: zxbpp must use <stdin> when no files given

src/api/optimize.py, tests/functional/arch/zx48k/for_const_crash1.asm, tests/functional/arch/zx48k/for_const_crash1.bas
=> fix: crash with FOR loop using constants

src/api/check.py, src/api/global_.py, src/symbols/call.py, src/symbols/id_/_id.py, tests/functional/arch/zx48k/bad_fname_err5.bas, tests/functional/arch/zx48k/bad_fname_err6.bas, tests/functional/cmdline/test_errmsg.txt
Sometimes, when including a file and having an error on a function call, the error shows the filename where the function was defined, not where the error actually happened.
=> fix: wrong filename in errors

docs/do.md, docs/end.md, docs/stop.md
=> doc: add STOP keyword

docs/pi.md
=> doc: add PI documentation

docs/ln.md
=> doc: adds LN documentation

docs/exp.md
=> doc: add EXP() documentation

src/lib/arch/zxnext/runtime/bound.asm, tests/functional/arch/zxnext/bound00.asm, tests/functional/arch/zxnext/bound00.bas, tests/functional/arch/zxnext/bound01.asm, tests/functional/arch/zxnext/bound01.bas, tests/functional/arch/zxnext/bound02.asm, tests/functional/arch/zxnext/bound02.bas, tests/functional/arch/zxnext/bound03.asm, tests/functional/arch/zxnext/bound03.bas, tests/functional/arch/zxnext/bound04.asm, tests/functional/arch/zxnext/bound04.bas, tests/functional/arch/zxnext/ubound0.asm, tests/functional/arch/zxnext/ubound0.bas
This is part of the fix for #963 but for zxnext.
=> fix: update bound routine in zxnext

.github/workflows/python-app.yml
Uses native pip cache from the python-setup GH Action.
Also removes pipeline run on mergeing.
=> feat: uses native pip cache in pipeline

tools/consolidate-libs.py
Many files in the libs/ directory are duplicated because most archs share a lot in common. Mantaining modification along all possible archs is tedious, so this tool hardlinks all identical files son modifying one is modifying all of them.
Git is agnostic to this.
=> feat: adds a tool to consolidate (hard-link) duplicated files

CHANGELOG.md, docs/overrides/stylesheets/extra.css, docs/sgn.md
=> Adds SGN.md page

docs/fastcall.md, docs/stdcall.md
=> docs: add stdcall.md page

src/lib/arch/zx48k/stdlib/putchars.bas, src/lib/arch/zxnext/stdlib/putchars.bas, tests/functional/arch/zx48k/stdlib_putchars.asm
Add `getPaintData()` and `getChars()` functions to putchars.bas  library.
These does the opposite of `putChars()` and `paint()` functions.
=> feat: add getPaintData and getChars functions

src/api/check.py, src/arch/z80/visitor/translator.py, src/arch/z80/visitor/translator_inst_visitor.py, src/symbols/argument.py, src/symbols/arrayaccess.py, src/symbols/arrayload.py
Now it's possible to do:
```basic
DIM a(2) As Ubyte
SUB Incr(ByRef x As Ubyte)
LET x = x + 1
END SUB
Incr(a(2))
```
So it's possible to pass single array elements as `ByRef` params whose value can be changed.
=> fix: implement ByRef with an Array Element
