- .bumpversion.cfg
- symbols/strslice.py
- tests/functional/strbase.asm
- tests/functional/strbase.bas
- tests/functional/strbase2.asm
- tests/functional/strbase2.bas
- version.py
- zxbparser.py
Fixes a bug with string-base option being ignored.
> Strbase fix

- .gitignore
More precisely:
* All the pyc files.
* Distributed egg bundles.
> Ignore some unwanted files and bundles

- api/symboltable.py
Rearranges some symbol table code for better clarification.
> refact: code cleanup

- tox.ini
And split them in differents folders.
> Enable Coverage for all environments

- symbols/arraydecl.py
- symbols/arrayload.py
- symbols/asm.py
- symbols/bound.py
- symbols/boundlist.py
- symbols/builtin.py
- symbols/function.py
- symbols/label.py
- symbols/number.py
- symbols/paramdecl.py
- symbols/paramlist.py
- symbols/string_.py
- symbols/strslice.py
- symbols/typecast.py
- symbols/var.py
- symbols/vararray.py
- symbols/vardecl.py
Replace ''' with """ in docstrings, and use
super() when required.
> Refactorize code

- setup.py
Version 1.9.1 uploaded, signaling python 2.x is dropped.
> Update setup.py file

- library/fastplot.bas
A fastplot routine library contributed to the Wiki by
Britlion and rearranged by J. Mcgibbitts
> Add fastplot library

- docs/archive.md
- docs/tutorials.md
Update version (it's 1.9.8 now). Also update broken links to some tutorials.
> Updated documentation

- arch/zx48k/optimizer/basicblock.py
Upon certain circumstances -O3 crashes if bb is None
> Fix crash with -O3

- tools/scrview.py
Made with python and pygame :-)
> Add a simple .SCR viewer

- library-asm/or32.asm
- tests/functional/or32.asm
> Refactorize OR32

- api/optimize.py
- api/utils.py
- symbols/__init__.py
- tests/functional/const6.asm
- tests/functional/const6.bas
Const might be a number or a "SymbolNUMBER". This is
something that might be refactored in the future.
> Fix a crash in some const cases

- examples/english/comecoquitos.bas
- examples/spanish/comecoquitos.bas
> Give credits to Pedro Guida for comecoquitos

- tests/functional/test.py
Since the compiler is imported as a module in the testing framework,
a crash on it will also crash the testing process.
Now it's trapped and reported with the ability to stop in the crash
for inspection or to continue (-E commandline flag)
> Allow compiler crashes to be trapped

- docs/archive.md
> Update spacing between download files

- src/api/identityset.py
Not it fulfills the Iterable interface
> Add typing to IdentitySet

- src/api/errmsg.py
- src/libzxbc/zxbparser.py
This will make the fastcall muteable
> Refact FASTCALL warning

- src/api/errmsg.py
- src/api/optimize.py
This will allow it to be silenced.
> Refactorice Func is never called

- src/arch/zx48k/library/input.bas
- src/arch/zxnext/library/input.bas
FLAGS var must be preserved entirely.
> Fix input breaking PAUSE

- src/api/optimize.py
- tests/functional/opt2_fastcall_func.asm
- tests/functional/opt2_fastcall_func.bas
- tests/functional/opt2_fastcall_sub.asm
- tests/functional/opt2_fastcall_sub.bas
- tests/functional/opt2_labelinfunc.asm
- tests/functional/opt2_labelinfunc3.asm
- tests/functional/opt2_labelinfunc4.asm
- tests/functional/opt2_labelinfunc5.asm
- tests/functional/opt2_unused_var.asm
- tests/functional/opt3_proc0.asm
Make functions with no parameters and local vars
as fastcall by default.
Thanks to @Duefectu!
> Add new optimization FASTCALL

- src/arch/zx48k/library-asm/copy_attr.asm
- src/arch/zx48k/translator.py
- src/arch/zx48k/translatorvisitor.py
- tests/functional/attr_in_subs.asm
- tests/functional/attr_in_subs.bas
- tests/functional/coercion3.asm
And also in functions. Ensure Attributes are updated
upon leaving the body (if the last instruction in a
SUB body is an ATTR one, it wont be completely finished
due to the traversal).
Also, chained attr functions are optimized.
> Ensure attrs are updated in SUBs

- docs/library.md
- docs/library/zx0.md
- src/arch/zx48k/library/zx0.bas
- src/arch/zxnext/library/zx0.bas
> added ZX0 support

- tools/nextcreator.py
> Fix bank counting bug in nextool

- src/arch/zx48k/translator.py
- tests/functional/array_check_param.asm
- tests/functional/array_check_param.bas
> Fixes crash on array_check

- docs/external_resources.md
Updated External Resources to add the syntax highlighter for Sublime Text
> Added Sublime syntax highlighter to External Resources

- docs/int.md
> Add INT doc

- src/api/config.py
- src/api/options.py
- src/arch/zx48k/backend/__init__.py
- src/zxbc/args_parser.py
- src/zxbc/zxbc.py
- src/zxbpp/zxbpp.py
- tests/api/test_config.py
- tests/api/test_symbolTable.py
- tests/cmdline/config_sample.ini
- tests/cmdline/test_zxb.py
- tests/functional/test_cmdline.txt
- tests/symbols/test_symbolARRAYACCESS.py
- tests/symbols/test_symbolBINARY.py
- tests/symbols/test_symbolBOUND.py
- tests/symbols/test_symbolTYPECAST.py
Now every action is done through OPTIONS(...) call method.
> Refactorize Options container.

- src/arch/zx48k/library/zx0.bas
- src/arch/zxnext/library/zx0.bas
The compressed file format was slightly changed in ZX0 version 2. This new file format allowed ZX0 decompressors to be slightly smaller and run slightly faster. This update modifies "ZX0.bas" library to use ZX0 version 2 instead of deprecated ZX0 version 1.
> Improved ZX0 v2 file format

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- tox.ini
> build: add pre-commit hooks

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- src/arch/z80/backend/_f16.py
- src/arch/z80/beep.py
- src/arch/z80/translator.py
- src/arch/z80/translatorvisitor.py
- src/arch/zx48k/beep.py
- src/symbols/binary.py
- src/zxbasm/expr.py
- src/zxbc/zxbparser.py
This will add support for python 3.10+
> build: update project dependencies

- src/arch/z80/peephole/evaluator.py
- src/arch/z80/peephole/opts/054_o3_ld_a_N_ld_hl_a.opt
- tests/functional/zx48k/opt3_haplo05.asm
Do some extra optimization with constants
> feat: add opt54 optimizer recipe

- src/arch/z80/translator.py
- src/arch/zx48k/library-asm/strarraycpy.asm
- tests/functional/zx48k/arraycopy5.asm
- tests/functional/zx48k/arraycopy5.bas
Fix bug when copying arrays of strings.
> fix: array a$=b$ assignation

- src/zxbc/zxbparser.py
- tests/functional/zx48k/save04.asm
- tests/functional/zx48k/save04.bas
SAVE command was not typecasting start and
length values to UInteger. Fixed.
> fix: fixes SAVE command

- tests/functional/test.py
Test in subfolder zxnext should be updated using arch=zxnext. The same applies for other future architectures.
Also types all the test.py tool.
> fix: test updates were not taking arch into account

- setup.py
- src/arch/__init__.py
- src/arch/z80/optimizer/basicblock.py
- src/arch/z80/optimizer/cpustate.py
- src/arch/z80/optimizer/flow_graph.py
- src/arch/z80/optimizer/helpers.py
- src/arch/z80/optimizer/labels_dict.py
- src/arch/z80/optimizer/main.py
- src/arch/z80/optimizer/memcell.py
- src/arch/zxnext/__init__.py
- src/arch/zxnext/optimizer/__init__.py
- src/arch/zxnext/optimizer/basicblock.py
- src/arch/zxnext/optimizer/cpustate.py
- src/arch/zxnext/optimizer/main.py
- src/arch/zxnext/optimizer/memcell.py
- src/zxbc/zxbc.py
- tests/arch/zx48k/optimizer/test_basicblock.py
- tests/arch/zx48k/optimizer/test_cpustate.py
- tests/functional/zxnext/opt4_mul8.asm
- tests/functional/zxnext/opt4_mul8.bas
- tools/normalize_bas.py
- zxb.py
- zxbasm.py
- zxbc.py
- zxbpp.py
ZX Next MUL instruction dependencies were not implemented in the optimizer.
> fix: implement ZX Next MUL dependencies

- pyproject.toml
- src/arch/z80/optimizer/basicblock.py
- src/arch/z80/peephole/evaluator.py
- src/arch/z80/peephole/parser.py
- src/ply/lex.py
- src/ply/yacc.py
- src/symbols/type_.py
- src/zxbpp/base_pplex.py
- src/zxbpp/zxbpp.py
- tools/scrview.py
https://mypy.readthedocs.io/en/stable/error_code_list.html#check-indexing-operations-index
> REF: Enable "index" check in mypy

- pyproject.toml
Waiting for: https://github.com/boriel/zxbasic/pull/712
> Improve linter folder management

- pyproject.toml
- src/symbols/block.py
- src/symbols/type_.py
https://docs.astral.sh/ruff/rules/unnecessary-comprehension-in-call/
> fix: Ruff rule C419 (unnecessary-comprehension-in-call)

- .github/workflows/python-app.yml
- LICENSE.txt
- README.md
Fix wrong licensing (typo). Should read AGPL (not GPL).
> doc: fix license to AGPLv3

- pyproject.toml
- src/ply/lex.py
- src/ply/yacc.py
- src/symbols/type_.py
- src/zxbasm/asmlex.py
- src/zxbasm/basic.py
- src/zxbpp/prepro/args.py
- tests/functional/test.py
https://docs.astral.sh/ruff/rules/useless-object-inheritance/
> fix: Ruff rule UP004 (useless-object-inheritance)

- poetry.lock
- pyproject.toml
See: https://python-poetry.org/docs/managing-dependencies/
> feat: use new Poetry group convention definition

- src/lib/arch/zxnext/stdlib/NextLibLite.bas
This is a stripped down version of @em00k's awesome NextLib.bas library trimmed down by @Duefectu.
> feat: add NextLibLite.bas library

- pyproject.toml
- src/api/optimize.py
- src/arch/z80/optimizer/main.py
- src/arch/z80/optimizer/memcell.py
- src/arch/z80/visitor/translator_visitor.py
- src/ast/tree.py
- src/symbols/id_/ref/symbolref.py
https://docs.astral.sh/ruff/rules/explicit-f-string-type-conversion/
> feat: fix Ruff rule RUF010

- src/arch/z80/backend/_32bit.py
Also remove 2 TODOs comments since these lines are hit by test.
> refact: improve typing

- src/arch/interface/quad.py
- src/arch/z80/backend/_parray.py
- src/arch/z80/backend/_pload.py
- src/arch/z80/backend/common.py
- src/arch/z80/backend/generic.py
- src/arch/z80/backend/quad.py
Now we can choose between ix and iy.
Also does some minor refacts.
> feat: make IDX_REGISTER configurable

- pyproject.toml
- src/arch/z80/backend/_float.py
- src/arch/zxnext/__init__.py
- src/arch/zxnext/backend/generic.py
- src/zxbc/zxbparser.py
- tests/arch/zx48k/peephole/test_parser.py
- tests/functional/test.py
- zxb.py
- zxbasm.py
- zxbc.py
- zxbpp.py
https://docs.astral.sh/ruff/rules/unused-noqa/#unused-noqa-ruf100
> fix: Ruff rule RUF100 (unused-qa)

- pyproject.toml
- src/api/symboltable/symboltable.py
- src/arch/z80/backend/_f16.py
https://docs.astral.sh/ruff/rules/redefined-argument-from-local/
> fix: Ruff rule PLR1704 (redefined-argument-from-local)

- pyproject.toml
- tests/functional/test.py
https://docs.astral.sh/ruff/rules/self-assigning-variable/
> fix: Ruff rule PLW0127 (self-assigning-variable)

- docs/bitwiselogic.md
Fixes wrong sample result for bAND (see #870)
> fix: fixes doc issue

- docs/code.md
- docs/library/asc.bas.md
> fix: broken links in ASC library function

- docs/identifier.md
- docs/library/csrlin.md
- docs/library/point.md
- docs/library/pos.md
- docs/library/screen.md
> doc: add POINT documentation

- pyproject.toml
- src/ply/yacc.py
https://docs.astral.sh/ruff/rules/superfluous-else-raise/
> fix: Ruff rule RET506 (superfluous-else-raise)

- pyproject.toml
- Use new more generic emails
- Update repo URL
- Update project URL
> build: change pkg metadata.
